name: CI

on:
  pull_request:
    branches:
      - main

jobs:
  ci-changes:
    runs-on: ubuntu-latest
    outputs:
      src: ${{ steps.changes.outputs.src }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Paths Filter
        id: changes
        uses: dorny/paths-filter@v3.0.2
        with:
          filters: |
            src:
              - 'vite.config.mts'
              - 'load-context.ts'
              - 'env.d.ts'
              - 'tsconfig.json'
              - 'app/**'
              - 'functions/**'

  ci-biome:
    runs-on: ubuntu-latest
    needs: ci-changes
    if: ${{ needs.ci-changes.outputs.src == 'true' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Biome
        uses: biomejs/setup-biome@v2.1.1
        with:
          version: latest

      - name: Biome check
        run: biome check ./app

  ci-build:
    runs-on: ubuntu-latest
    needs: ci-biome
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x

      - name: Setup Pnpm
        uses: pnpm/action-setup@v3.0.0
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/pages-action@1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: blog
          directory: ./public
          gitHubToken: ${{ secrets.GTIHUB_TOKEN }}

