name: Deploy to Cloudflare Pages

on:
  pull_request:
    branches:
      - main
    types: [closed]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: github.event.pull_request.merged == true

    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1

      - name: Setup Node
        uses: actions/setup-node@v4.0.2
        with:
          node-version: 20.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v2.4.0
        with:
          version: 8
          run_install: false

      - name: Install dependencies
        run: pnpm install

      - name: Build
        run: pnpm run build

      - name: Paths Filter
        id: changes
        uses: dorny/paths-filter@v3.0.2
        with:
          filters: |
            src:
              - 'app/**'

      - name: Deploy to Cloudflare Pages
        if: steps.changes.outputs.src == 'true'
        uses: cloudflare/pages-action@1
        with:
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          projectName: blog
          directory: ./public
          gitHubToken: ${{ secrets.GTIHUB_TOKEN }}
